// src/react/src/Nav.js
import React, { Component } from 'react';

class Nav extends Component {
  render() {
    return (
    <nav className="navbar navbar-dark bg-dark">
        <a className="navbar-brand" href="react">To Do Lists</a>
        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
        </button>

        <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <ul className="navbar-nav mr-auto">
            <li className="nav-item active">
                <a className="nav-link" href="react">Home <span className="sr-only">(current)</span></a>
            </li>
            </ul>
        </div>
    </nav>

    );
  }
}

export default Nav;

// src/angular/src/app/nav/nav.component.ts
import { Component, OnInit } from '@angular/core';
import { AppComponent } from '../app.component'
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { EditModal } from '../modal/edit-modal/edit-modal.component';
import { AppService } from '../app.service'

@Component({
  selector: 'app-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.css']
})
export class NavComponent implements OnInit {

  constructor(private app: AppComponent, private appService: AppService, private modal: NgbModal) { }

  ngOnInit() {
  }

  addList() {
    let modalRef = this.modal.open(EditModal);

    modalRef.componentInstance.options = {
      heading: "Add new list",
      list: {name: "", items:[{name:"", completed:false}]},
      confirm: "Add",
      cancel: "Cancel"
    }

    modalRef.result.then((data) => {
      let response = this.appService.addList(data);
      console.log("response", response);
      this.app.lists.push(data);
    }).catch((data) => {
      console.log("Add cancelled", data)
    });
  }

}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">To Do Lists</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="angular">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
          <button class="btn btn-primary" (click)="addList()">Add List</button>
        </li>
    </ul>
  </div>
</nav>
