// src/angular/src/app/modal/confirm-modal/confirm-modal.component.ts
import {Component, Input} from '@angular/core';

import {NgbModal, NgbActiveModal} from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'confirm-modal',
  templateUrl: `./confirm-modal.component.html`
})
export class ConfirmModal {
  @Input() name;

  constructor(public activeModal: NgbActiveModal) {}
}
<div class="modal-header">
  <h4 class="modal-title">{{ options.header }}</h4>
  <button type="button" class="close" aria-label="Close" (click)="activeModal.dismiss('Cross click')">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <p>{{ options.message }}</p>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-danger" (click)="activeModal.close('Confirm')">{{options.confirm}}</button>
  <button type="button" class="btn btn-outline-light" (click)="activeModal.dismiss('Cancel')">{{options.cancel}}</button>
</div>

// src/vue/src/components/ConfirmModal.vue
<template>
    <div class="modal fade" v-bind:id="id"  role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editModalLabel">Delete List</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete {{list.name}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" v-on:click="confirm(list._id)" data-dismiss="modal">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
  name: 'confirmmodal',
  props: ['id', 'list', 'confirm']
}
</script>
