// src/angular/src/app/modal/edit-modal/edit-modal.component.ts
import {Component, Input} from '@angular/core';

import {NgbModal, NgbActiveModal} from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'edit-modal',
  templateUrl: `./edit-modal.component.html`
})
export class EditModal {
  @Input() name;

  constructor(public activeModal: NgbActiveModal) {}
}
<div class="modal-header">
  <h4 class="modal-title">{{ options.header }}</h4>
  <button type="button" class="close" aria-label="Close" (click)="activeModal.dismiss('Cross click')">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <form>
      <div class="form-group">
        <label for="name">List Name</label>
        <input [(ngModel)]="options.list.name" name="name" class="form-control" style="font-weight:bold;" required/>
      </div>
      <div class="form-group" *ngFor="let item of options.list.items; let i = index;">
        <div class="input-group">
          <input [(ngModel)]="options.list.items[i].name" name="list-item-{{ i }}" class="form-control" required/>
          <div class="input-group-append">
              <button class="btn btn-outline-danger" id="remove-list-item-{{ i }}" (click)="options.list.items.splice(i, 1);">X</button>
          </div>
        </div>
      </div>
      <button class="btn btn-outline-primary form-control" (click)="options.list.items.push({name:'', complete:false})">+</button>
  </form>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-danger" (click)="activeModal.close(options.list)">{{ options.confirm }}</button>
  <button type="button" class="btn btn-outline-light" (click)="activeModal.dismiss('Cancel')">{{ options.cancel }}</button>
</div>

// src/vue/src/components/EditModal.vue
<template>
    <div class="modal fade" v-bind:id="id"  role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editModalLabel">Edit List</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <input v-model="list.name" name="name" class="form-control" style="font-weight: 'bold'" placeholder="List Name" required />
                        </div>
                        <div v-for="(list, index) in list.items" v-bind:key="index" class="form-group">
                            <div class="input-group">
                                <input v-model="list.name" name="list-item" class="form-control" placeholder="List Item" required />
                                <div class="input-group-append">
                                    <button v-on:click="removeItem(index)" type="button" class="btn btn-outline-danger">X</button>
                                </div>
                            </div>
                        </div>
                        <button v-on:click="addEmptyItem()" type="button" class="btn btn-outline-primary form-control">+</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" v-on:click="confirm(list)" data-dismiss="modal">Save changes</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
  name: 'editmodal',
  methods: {
    removeItem (index) {
      let newList = Object.assign({}, this.list)
      newList.items.splice(index, 1)

      this.list = newList
    },
    addEmptyItem () {
      let newList = Object.assign({}, this.list)
      newList.items.push(Object.assign({}, this.emptyItem))

      this.list = newList
    }
  },
  props: ['id', 'list', 'confirm'],
  data () {
    return {
      emptyItem: { name: '', completed: false }
    }
  }
}
</script>
